### ISSUE TITLE
How to reset PAT

### ISSUE THREAD

**Issue by aerolalit** [cschleiden/vscode-github-actions#22]
I accidentally entered wrong github PAT.  Not it gives following error message. 

` :( An error has occured while retrieving workflows: Bad credentials`

Any idea how I can re-enter the PAT?

**Comment by cschleiden** [comment]
You can invoke the "Login" command from the command palette (Cmd/Ctrl-Shift-P by default):

![image](https://user-images.githubusercontent.com/2201819/81995459-4c729c00-95ff-11ea-9025-3004262c4a48.png)

**Comment by NickLarsenNZ** [comment]
I can't find this menu item in mine. My repo is checked out via SSH if that changes anything:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/10092581/119276915-cc026480-bc70-11eb-8572-47c5609e96c5.png">

**Comment by NickLarsenNZ** [comment]
I managed to get it to work by Signing in at the bottom left of vs code:

<img width="73" alt="image" src="https://user-images.githubusercontent.com/10092581/119277073-a88be980-bc71-11eb-8a0e-65a82886da21.png">

Then followed these instructions (because I got error 801): https://github.com/microsoft/vscode-pull-request-github/issues/1221#issuecomment-565816950
